# Created using wingetcreate 1.2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: TexasInstruments.TIConnectCE
PackageVersion: 6.0.0.2688
DefaultLocale: fr-FR
ManifestType: version
ManifestVersion: 1.4.0
